// toplamda event sayısı: 47

import arabMoney from "../../public/events/arab-money.webp";
import angryPolitician from "../../public/events/angry-politician-3.webp";
import alperGezeravcı from "../../public/events/alper-gezeravci.webp";
import dataHack from "../../public/events/data-hack.webp";
import electricalShortcut from "../../public/events/electrical-shortcut.webp";
import foodCrisis from "../../public/events/food-crisis.webp";
import gangActivities from "../../public/events/gang-activities.webp";
import InterventionAbroad from "../../public/events/intervention-abroad.webp";
import IsraelPalestine from "../../public/events/israel-palestine.webp";
import nuclearThesisExplosion from "../../public/events/nuclear-thesis-explosion.webp";
import oilSpill from "../../public/events/oil-spill.webp";
import peopleOverjoyed from "../../public/events/people-overjoyed.webp";
import politicianMercedes from "../../public/events/politicians-mercedes.webp";
import peopleProtesting from "../../public/events/people-protesting.webp";
import shakiraConcert from "../../public/events/shakira-concert.webp";
import streetElectricalDeath from "../../public/events/street-electrical-death.webp";
import terroristBusted from "../../public/events/terrorists-busted.webp";
import tosuncuk from "../../public/events/tosuncuk.webp";
import waterPipesExploded from "../../public/events/water-pipes-exploded.webp";
import womenAbuseOnstreet from "../../public/events/women-abuse-onstreet.webp";
import helaviyeIntervene from "../../public/events/syria-intervention.webp";
import tbmmFight from "../../public/events/tbmm-fight.webp";
import peopleLeavingCountry from "../../public/events/people-leaving-country.webp";
import droughtLake from "../../public/events/drought-lake.webp";
import forestFire from "../../public/events/forest-fire-disaster.webp";
import gasDiscovery from "../../public/events/gas-discovery.webp";
import tourismSeason from "../../public/events/tourism-season.webp";
import civilSubordinate from "../../public/events/civil-subordinate.webp";
import mineCollapsed from "../../public/events/mine-collapsed.webp";
import damWaterShortage from "../../public/events/dam-water-shortage.webp";
import newFactoryOpening from "../../public/events/new-factory-opening.webp";
import underSeaCables from "../../public/events/undersea-cables.webp";
import recycleFactory from "../../public/events/recycle-factory.webp";
import spaceCenter from "../../public/events/space-center.webp";
import farm from "../../public/events/farm.webp";
import farmEducation from "../../public/events/farm-education.webp";
import agricultureComp from "../../public/events/agriculture-big-comp.webp";
import scholarship from "../../public/events/scholarship.webp";
import bribeMoney from "../../public/events/bribe-money.webp";
import censor from "../../public/events/journalist-censor.webp";
import wasteFruit from "../../public/events/waste-fruit.webp";
import getSick from "../../public/events/hastalandın.webp";
import illuminati from "../../public/events/france-olympic-ritual.webp";
import meteor from "../../public/events/meteor.webp";
import pandemic from "../../public/events/pandemic.webp";

export const events = [
    {
        id: 501,
        photo: arabMoney,
        title: {
            tr: "Ortadoğu Ülkelerinden Beklenmedik Yatırım!",
            en: "Unexpected Investment from Middle Eastern Countries!",
            fr: "Investissement Inattendu des Pays du Moyen-Orient!",
            de: "Unerwartete Investition aus den Ländern des Nahen Ostens!",
            zh: "来自中东国家的意外投资！",
            es: "¡Inversión inesperada de países de Oriente Medio!",
            pt: "Investimento Inesperado de Países do Oriente Médio!",
            ru: "Неожиданная инвестиция из стран Ближнего Востока!",
        },
        description: {
            tr: "Ortadoğu ülkelerinden gelen ani para akışı ekonomik toparlanma umutlarını yeşertti. Bu zenginlik nasıl kullanılacak, en çok kimler fayda sağlayacak?",
            en: "A sudden influx of funds from Middle Eastern countries has revived hopes for economic recovery. How will this wealth be used, and who will benefit the most?",
            fr: "Un afflux soudain de fonds en provenance des pays du Moyen-Orient a ravivé les espoirs de reprise économique. Comment cette richesse sera-t-elle utilisée, et qui en bénéficiera le plus ?",
            de: "Ein plötzlicher Zustrom von Mitteln aus den Ländern des Nahen Ostens hat die Hoffnungen auf eine wirtschaftliche Erholung wiederbelebt. Wie wird dieser Reichtum genutzt und wer wird am meisten profitieren?",
            zh: "来自中东国家的资金突然涌入，复兴了经济复苏的希望。这笔财富将如何使用，谁将受益最多？",
            es: "Una repentina afluencia de fondos de países de Oriente Medio ha reavivado las esperanzas de recuperación económica. ¿Cómo se usará esta riqueza y quién se beneficiará más?",
            pt: "Um influxo repentino de fundos de países do Oriente Médio reacendeu as esperanças de recuperação econômica. Como essa riqueza será usada e quem mais se beneficiará?",
            ru: "Внезапный приток средств из стран Ближнего Востока возродил надежды на экономическое восстановление. Как это богатство будет использовано и кто получит наибольшую выгоду?",
        },
        effects: {
            budget: +25,
        },
    },
    {
        id: 502,
        photo: dataHack,
        title: {
            tr: "Ulusal Veri Sızıntısı!",
            en: "National Data Breach!",
            fr: "Fuite de Données Nationales!",
            de: "Nationale Datenpanne!",
            zh: "国家数据泄露！",
            es: "¡Fuga de datos nacionales!",
            pt: "Vazamento de Dados Nacionais!",
            ru: "Национальная утечка данных!",
        },
        description: {
            tr: "Ülkenin kimlik sistemi hacklendi! Milyonlarca kişinin hassas verileri siber suçluların elinde. Güvenlik uzmanları hasarı önlemek için seferber halinde.",
            en: "The country's identity system was hacked! Millions of people's sensitive data are in the hands of cybercriminals. Security experts are mobilized to prevent damage.",
            fr: "Le système d'identité du pays a été piraté! Les données sensibles de millions de personnes sont entre les mains de cybercriminels. Les experts en sécurité sont mobilisés pour éviter les dégâts.",
            de: "Das Identitätssystem des Landes wurde gehackt! Die sensiblen Daten von Millionen von Menschen sind in den Händen von Cyberkriminellen. Sicherheitsexperten sind mobilisiert, um Schäden zu verhindern.",
            zh: "国家的身份系统被黑客攻击！数百万人的敏感数据落入网络犯罪分子手中。安全专家正在全力防止损失。",
            es: "¡El sistema de identidad del país fue hackeado! Los datos sensibles de millones de personas están en manos de ciberdelincuentes. Los expertos en seguridad están movilizados para prevenir daños.",
            pt: "O sistema de identidade do país foi hackeado! Dados sensíveis de milhões de pessoas estão nas mãos de cibercriminosos. Especialistas em segurança estão mobilizados para evitar danos.",
            ru: "Система идентификации страны была взломана! Чувствительные данные миллионов людей оказались в руках киберпреступников. Эксперты по безопасности мобилизованы для предотвращения ущерба.",
        },
        effects: {
            internalSecurity: -15,
            publicSupport: -15,
        },
    },
    {
        id: 503,
        photo: electricalShortcut,
        title: {
            tr: "Elektrik Kesintisi Kaosu!",
            en: "Electricity Outage Chaos!",
            fr: "Chaos de Coupure d'Électricité!",
            de: "Chaos durch Stromausfall!",
            zh: "电力中断混乱！",
            es: "¡Caos por apagón eléctrico!",
            pt: "Caos de Interrupção de Eletricidade!",
            ru: "Хаос из-за отключения электричества!",
        },
        description: {
            tr: "Ani bir elektrik kesintisi şehirde hayatı durma noktasına getirdi. Sokaklarda kaos hakim, insanlar temel ihtiyaçlarına ulaşmakta zorlanıyor!",
            en: "A sudden power outage brought the city to a standstill. Chaos reigns in the streets, and people struggle to access basic necessities!",
            fr: "Une panne de courant soudaine a paralysé la ville. Le chaos règne dans les rues, et les gens ont du mal à accéder aux nécessités de base!",
            de: "Ein plötzlicher Stromausfall brachte die Stadt zum Stillstand. Chaos herrscht auf den Straßen, und die Menschen kämpfen darum, grundlegende Bedürfnisse zu erfüllen!",
            zh: "突如其来的停电使城市陷入瘫痪。街道上混乱不堪，人们难以获得基本生活必需品！",
            es: "Un corte de electricidad repentino dejó la ciudad paralizada. ¡El caos reina en las calles y la gente lucha por acceder a lo básico!",
            pt: "Uma queda de energia repentina parou a cidade. O caos reina nas ruas e as pessoas lutam para acessar necessidades básicas!",
            ru: "Внезапное отключение электроэнергии парализовало город. На улицах царит хаос, люди борются за доступ к базовым нуждам!",
        },
        effects: {
            infrastructureAndEnvironment: -20,
            publicSupport: -15,
        },
    },
    {
        id: 504,
        photo: foodCrisis,
        title: {
            tr: "Gıda Krizi Patlak Verdi!",
            en: "Food Crisis Erupts!",
            fr: "Crise Alimentaire Éclate!",
            de: "Lebensmittelkrise Bricht Aus!",
            zh: "食品危机爆发！",
            es: "¡Estalla la crisis alimentaria!",
            pt: "Crise Alimentar Eclode!",
            ru: "Разразился продовольственный кризис!",
        },
        description: {
            tr: "Temel gıda kaynakları hızla tükeniyor, market rafları boş! Halk endişe içinde, yetkililer acil çözümler arıyor.",
            en: "Basic food supplies are running out quickly, and store shelves are empty! People are worried, and authorities are seeking urgent solutions.",
            fr: "Les approvisionnements alimentaires de base s'épuisent rapidement, et les étagères des magasins sont vides! Les gens s'inquiètent, et les autorités cherchent des solutions urgentes.",
            de: "Grundlegende Lebensmittelvorräte gehen schnell zur Neige, und die Regale der Geschäfte sind leer! Die Menschen sind besorgt, und die Behörden suchen nach dringenden Lösungen.",
            zh: "基本食品供应迅速耗尽，商店货架空空如也！人们感到担忧，当局正在寻求紧急解决方案。",
            es: "Los suministros básicos de alimentos se están agotando rápidamente y los estantes de las tiendas están vacíos. ¡La gente está preocupada y las autoridades buscan soluciones urgentes!",
            pt: "Os suprimentos básicos de alimentos estão acabando rapidamente e as prateleiras das lojas estão vazias. As pessoas estão preocupadas e as autoridades buscam soluções urgentes.",
            ru: "Основные запасы продовольствия быстро заканчиваются, а полки магазинов пусты! Люди обеспокоены, власти ищут срочные решения.",
        },
        effects: {
            agriculturalProduction: -20,
            publicSupport: -15,
        },
    },
    {
        id: 505,
        photo: InterventionAbroad,
        title: {
            tr: "Dış Müdahale Tehlikesi!",
            en: "Danger of Foreign Intervention!",
            fr: "Danger d'Intervention Étrangère!",
            de: "Gefahr der Ausländischen Intervention!",
            zh: "外国干预的危险！",
            es: "¡Peligro de Intervención Extranjera!",
            pt: "Perigo de Intervenção Estrangeira!",
            ru: "Опасность иностранного вмешательства!",
        },
        description: {
            tr: "Dış ülkeler ülkemizin iç işlerine müdahale etmeye çalışıyor.",
            en: "Foreign countries are trying to interfere in our country's internal affairs.",
            fr: "Les pays étrangers tentent d'intervenir dans les affaires intérieures de notre pays.",
            de: "Ausländische Länder versuchen, sich in die inneren Angelegenheiten unseres Landes einzumischen.",
            zh: "外国试图干涉我国的内政。",
            es: "Los países extranjeros están intentando interferir en los asuntos internos de nuestro país.",
            pt: "Países estrangeiros estão tentando interferir nos assuntos internos do nosso país.",
            ru: "Иностранные государства пытаются вмешаться во внутренние дела нашей страны.",
        },
        effects: {
            internationalRelations: -15,
            publicSupport: -10,
        },
    },
    {
        id: 506,
        photo: IsraelPalestine,
        title: {
            tr: "Orta Doğu’da Gerilim Tırmanıyor!",
            en: "Tensions Rise in the Middle East!",
            fr: "Les Tensions Montent au Moyen-Orient!",
            de: "Die Spannungen im Nahen Osten Steigen!",
            zh: "中东局势紧张升级！",
            es: "¡Las Tensiones Aumentan en el Medio Oriente!",
            pt: "As Tensões Aumentam no Oriente Médio!",
            ru: "Напряженность на Ближнем Востоке нарастает!",
        },
        description: {
            tr: "İsrail, Filistin'i bombalıyor! Bölgedeki tansiyon hızla yükseliyor. Küresel çapta tansiyon artıyor...",
            en: "Israel is bombing Palestine! Tensions are rapidly escalating in the region. Global tensions are also rising...",
            fr: "Israël bombarde la Palestine! Les tensions montent rapidement dans la région. Les tensions mondiales augmentent également...",
            de: "Israel bombardiert Palästina! Die Spannungen in der Region eskalieren schnell. Auch die globalen Spannungen nehmen zu...",
            zh: "以色列正在轰炸巴勒斯坦！该地区的紧张局势迅速升级。全球紧张局势也在加剧...",
            es: "¡Israel está bombardeando Palestina! Las tensiones están aumentando rápidamente en la región. Las tensiones globales también están aumentando...",
            pt: "Israel está bombardeando a Palestina! As tensões estão aumentando rapidamente na região. As tensões globais também estão aumentando...",
            ru: "Израиль бомбит Палестину! Напряженность в регионе стремительно растет. Глобальная напряженность также усиливается...",
        },
        effects: {
            internationalRelations: -20,
        },
    },
    {
        id: 507,
        photo: nuclearThesisExplosion,
        title: {
            tr: "Nükleer Tesiste Korkunç Patlama!",
            en: "Horrific Explosion at Nuclear Facility!",
            fr: "Explosion Horrible dans une Installation Nucléaire!",
            de: "Schreckliche Explosion in einer Nuklearanlage!",
            zh: "核设施发生可怕的爆炸！",
            es: "¡Horrible Explosión en una Instalación Nuclear!",
            pt: "Explosão Horrível em uma Instalação Nuclear!",
            ru: "Ужасный взрыв на ядерном объекте!",
        },
        description: {
            tr: "Nükleer tesiste büyük bir patlama gerçekleşti! Radyoaktif sızıntı endişesi tüm ülkeye yayılıyor, yetkililer krizle başa çıkmaya çalışıyor.",
            en: "A massive explosion occurred at a nuclear facility! Fears of radioactive leakage are spreading across the country as authorities struggle to handle the crisis.",
            fr: "Une explosion massive s'est produite dans une installation nucléaire! Les craintes de fuites radioactives se répandent dans tout le pays alors que les autorités luttent pour gérer la crise.",
            de: "Eine massive Explosion ereignete sich in einer Nuklearanlage! Ängste vor radioaktiven Lecks breiten sich im ganzen Land aus, während die Behörden versuchen, die Krise zu bewältigen.",
            zh: "核设施发生了巨大的爆炸！当局努力应对危机的同时，放射性泄漏的担忧正在全国蔓延。",
            es: "¡Ocurrió una gran explosión en una instalación nuclear! Los temores de fugas radiactivas se están extendiendo por todo el país mientras las autoridades luchan por manejar la crisis.",
            pt: "Uma grande explosão ocorreu em uma instalação nuclear! Os temores de vazamento radioativo estão se espalhando pelo país enquanto as autoridades lutam para lidar com a crise.",
            ru: "На ядерном объекте произошел мощный взрыв! Опасения радиоактивной утечки распространяются по всей стране, пока власти пытаются справиться с кризисом.",
        },
        effects: {
            infrastructureAndEnvironment: -15,
            agriculturalProduction: -15,
        },
    },
    {
        id: 508,
        photo: oilSpill,
        title: {
            tr: "Denizde Petrol Felaketi!",
            en: "Oil Disaster at Sea!",
            fr: "Catastrophe Pétrolière en Mer!",
            de: "Ölkatastrophe auf See!",
            zh: "海上石油灾难！",
            es: "¡Desastre Petrolero en el Mar!",
            pt: "Desastre de Petróleo no Mar!",
            ru: "Нефтяная катастрофа в море!",
        },
        description: {
            tr: "Tonlarca petrol denize döküldü, çevre kirliliği korkunç boyutlara ulaşıyor. Deniz yaşamı büyük tehdit altında!",
            en: "Tons of oil have spilled into the sea, causing devastating pollution. Marine life is under severe threat!",
            fr: "Des tonnes de pétrole se sont déversées dans la mer, provoquant une pollution dévastatrice. La vie marine est gravement menacée!",
            de: "Tonnenweise Öl sind ins Meer gelangt und verursachen verheerende Verschmutzungen. Das Meeresleben ist stark bedroht!",
            zh: "大量石油泄漏入海，造成严重污染。海洋生物面临严重威胁！",
            es: "Toneladas de petróleo se han derramado en el mar, causando una contaminación devastadora. ¡La vida marina está bajo una grave amenaza!",
            pt: "Toneladas de petróleo derramaram no mar, causando uma poluição devastadora. A vida marinha está sob grave ameaça!",
            ru: "Тонны нефти пролились в море, вызывая разрушительное загрязнение. Морская жизнь находится под серьезной угрозой!",
        },
        effects: {
            infrastructureAndEnvironment: -15,
            agriculturalProduction: -15,
        },
    },
    {
        id: 509,
        photo: peopleOverjoyed,
        title: {
            tr: "Halk Coşkuyla Sokaklarda!",
            en: "People Overjoyed in the Streets!",
            fr: "Les Gens en Liesse dans les Rues!",
            de: "Menschen Jubeln auf den Straßen!",
            zh: "人们在街头狂欢！",
            es: "¡Gente Feliz en las Calles!",
            pt: "Pessoas Exultantes nas Ruas!",
            ru: "Люди в восторге на улицах!",
        },
        description: {
            tr: "Umut dolu haberler sonrası halk sokaklarda kutlama yapıyor. Bu coşku ülkeye yayılırken, hükümetin popülerliği artıyor.",
            en: "After hopeful news, people are celebrating in the streets. This joy spreads throughout the country, boosting the government's popularity.",
            fr: "Après des nouvelles pleines d'espoir, les gens célèbrent dans les rues. Cette joie se propage dans tout le pays, augmentant la popularité du gouvernement.",
            de: "Nach hoffnungsvollen Nachrichten feiern die Menschen auf den Straßen. Diese Freude breitet sich im ganzen Land aus und stärkt die Popularität der Regierung.",
            zh: "在充满希望的消息传来后，人们在街头庆祝。这种欢乐在全国蔓延，提升了政府的声望。",
            es: "Después de noticias esperanzadoras, la gente está celebrando en las calles. Esta alegría se extiende por todo el país, aumentando la popularidad del gobierno.",
            pt: "Após notícias esperançosas, as pessoas estão comemorando nas ruas. Essa alegria se espalha por todo o país, aumentando a popularidade do governo.",
            ru: "После обнадеживающих новостей люди празднуют на улицах. Эта радость охватывает всю страну, увеличивая популярность правительства.",
        },
        effects: {
            publicSupport: +15,
            internalSecurity: +10,
        },
    },
    {
        id: 510,
        photo: peopleProtesting,
        title: {
            tr: "Hükümete Büyük İsyan!",
            en: "Massive Uprising Against the Government!",
            fr: "Grande Révolte Contre le Gouvernement!",
            de: "Massiver Aufstand gegen die Regierung!",
            zh: "针对政府的大规模抗议！",
            es: "¡Gran Rebelión Contra el Gobierno!",
            pt: "Grande Levante Contra o Governo!",
            ru: "Массовое восстание против правительства!",
        },
        description: {
            tr: "Azınlıklar hükümete karşı ayaklanıyor, meydanlarda protestolar büyüyor! Talepler karşılanacak mı?",
            en: "Minorities are rising against the government, and protests are growing in the squares! Will their demands be met?",
            fr: "Les minorités se soulèvent contre le gouvernement et les protestations s'intensifient sur les places! Leurs demandes seront-elles satisfaites?",
            de: "Minderheiten erheben sich gegen die Regierung, und die Proteste auf den Plätzen nehmen zu! Werden ihre Forderungen erfüllt?",
            zh: "少数群体正在对政府发起反抗，广场上的抗议活动不断扩大！他们的要求会被满足吗？",
            es: "¡Las minorías se están levantando contra el gobierno, y las protestas están creciendo en las plazas! ¿Se cumplirán sus demandas?",
            pt: "As minorias estão se levantando contra o governo, e os protestos estão crescendo nas praças! Suas demandas serão atendidas?",
            ru: "Меньшинства восстают против правительства, протесты на площадях набирают обороты! Будут ли выполнены их требования?",
        },
        effects: {
            publicSupport: -10,
            internalSecurity: -10,
        },
    },
    {
        id: 511,
        photo: shakiraConcert,
        title: {
            tr: "Başkentte Shakira Konseri!",
            en: "Shakira Concert in the Capital!",
            fr: "Concert de Shakira dans la Capitale!",
            de: "Shakira-Konzert in der Hauptstadt!",
            zh: "首都的夏奇拉演唱会！",
            es: "¡Concierto de Shakira en la Capital!",
            pt: "Concerto de Shakira na Capital!",
            ru: "Концерт Шакиры в столице!",
        },
        description: {
            tr: "Uzun yıllar unutulmayacak bir konser! Hayranlar coşkuyla eğlenirken, etkinlik tüm ülkenin gündeminde.",
            en: "A concert to remember for years! Fans are enjoying themselves with great enthusiasm, and the event is the talk of the country.",
            fr: "Un concert inoubliable pour des années! Les fans s'amusent avec un grand enthousiasme et l'événement est au centre de toutes les discussions du pays.",
            de: "Ein unvergessliches Konzert für viele Jahre! Die Fans genießen es mit großer Begeisterung, und das Ereignis ist das Gesprächsthema des Landes.",
            zh: "一场值得多年铭记的演唱会！粉丝们热情高涨，整个国家都在谈论这场盛事。",
            es: "¡Un concierto para recordar durante años! Los fans disfrutan con gran entusiasmo, y el evento es el tema de conversación del país.",
            pt: "Um concerto para ser lembrado por anos! Os fãs estão se divertindo com grande entusiasmo, e o evento é o assunto do país.",
            ru: "Концерт, который запомнится на долгие годы! Фанаты наслаждаются с большим энтузиазмом, а событие обсуждают во всей стране.",
        },
        effects: {
            publicSupport: +10,
            internationalRelations: +10,
        },
    },
    {
        id: 512,
        photo: streetElectricalDeath,
        title: {
            tr: "Sokakta Elektrik Kazası: Ölüm!",
            en: "Electrical Accident in the Street: Death!",
            fr: "Accident Électrique dans la Rue : Mort!",
            de: "Elektrounfall auf der Straße: Tod!",
            zh: "街头电击事故：死亡！",
            es: "¡Accidente Eléctrico en la Calle: Muerte!",
            pt: "Acidente Elétrico na Rua: Morte!",
            ru: "Электрический несчастный случай на улице: смерть!",
        },
        description: {
            tr: "Gündüz vakti sokakta elektrik kaçağı nedeniyle iki kişi hayatını kaybetti. Halk şokta, altyapı ve güvenlik önlemleri sorgulanıyor.",
            en: "Two people lost their lives due to an electrical fault in the street during the day. People are in shock, and infrastructure and safety measures are being questioned.",
            fr: "Deux personnes ont perdu la vie à cause d'une défaillance électrique dans la rue en pleine journée. Les gens sont sous le choc et les mesures de sécurité et d'infrastructure sont remises en question.",
            de: "Zwei Menschen kamen tagsüber durch einen Stromausfall auf der Straße ums Leben. Die Menschen sind geschockt, und Infrastruktur- und Sicherheitsmaßnahmen werden in Frage gestellt.",
            zh: "白天街头的电力故障导致两人死亡。人们陷入震惊，对基础设施和安全措施提出质疑。",
            es: "Dos personas perdieron la vida debido a una falla eléctrica en la calle durante el día. La gente está en shock y se están cuestionando las medidas de seguridad e infraestructura.",
            pt: "Duas pessoas perderam a vida devido a uma falha elétrica na rua durante o dia. As pessoas estão em choque, e as medidas de infraestrutura e segurança estão sendo questionadas.",
            ru: "Двое людей погибли из-за электрического замыкания на улице днем. Люди в шоке, инфраструктура и меры безопасности подвергаются сомнению.",
        },
        effects: {
            infrastructureAndEnvironment: -10,
            internalSecurity: -10,
            publicSupport: -10,
        },
    },
    {
        id: 513,
        photo: terroristBusted,
        title: {
            tr: "Teröristler Kıskıvrak Yakalandı!",
            en: "Terrorists Caught Red-Handed!",
            fr: "Terroristes Pris en Flagrant Délit!",
            de: "Terroristen auf Frischer Tat Ertappt!",
            zh: "恐怖分子被当场抓获！",
            es: "¡Terroristas Atrapados con las Manos en la Masa!",
            pt: "Terroristas Pego em Flagrante!",
            ru: "Террористы пойманы с поличным!",
        },
        description: {
            tr: "Güvenlik güçleri teröristleri suçüstü yakaladı! Ancak şehir merkezinde güvenlik endişeleri devam ediyor.",
            en: "Security forces caught terrorists red-handed! However, security concerns persist in the city center.",
            fr: "Les forces de sécurité ont pris les terroristes en flagrant délit! Cependant, des préoccupations sécuritaires persistent dans le centre-ville.",
            de: "Sicherheitskräfte haben Terroristen auf frischer Tat ertappt! Dennoch bestehen im Stadtzentrum weiterhin Sicherheitsbedenken.",
            zh: "安全部队当场抓获了恐怖分子！然而，市中心的安全担忧仍然存在。",
            es: "¡Las fuerzas de seguridad atraparon a los terroristas con las manos en la masa! Sin embargo, las preocupaciones de seguridad persisten en el centro de la ciudad.",
            pt: "As forças de segurança pegaram os terroristas em flagrante! No entanto, as preocupações com a segurança persistem no centro da cidade.",
            ru: "Силы безопасности поймали террористов с поличным! Однако опасения по поводу безопасности в центре города остаются.",
        },
        effects: {
            internalSecurity: +20,
            publicSupport: +10,
        },
    },
    {
        id: 514,
        photo: tosuncuk,
        title: {
            tr: "Gıda Bank Skandalı: Halk Dolandırıldı!",
            en: "Food Bank Scandal: People Defrauded!",
            fr: "Scandale de la Banque Alimentaire : Les Gens Fraudeés!",
            de: "Lebensmittelbank-Skandal: Menschen Betrogen!",
            zh: "食品银行丑闻：人民被欺诈！",
            es: "¡Escándalo del Banco de Alimentos: Personas Estafadas!",
            pt: "Escândalo do Banco de Alimentos: Pessoas Defraudadas!",
            ru: "Скандал с продовольственным банком: люди обмануты!",
        },
        description: {
            tr: "Gıda Bank sahibinin halkın yatırımlarını alarak yurtdışına kaçtığı tespit edildi. Birçok insan birikimlerini kaybetti. Skandal ülke gündeminde büyük yankı uyandırıyor.",
            en: "The owner of Food Bank has been found to have fled abroad with people's investments. Many people lost their savings. The scandal is making waves in the country.",
            fr: "Le propriétaire de la Banque Alimentaire a été découvert en train de fuir à l'étranger avec les investissements des gens. Beaucoup de personnes ont perdu leurs économies. Le scandale fait grand bruit dans le pays.",
            de: "Der Eigentümer der Lebensmittelbank wurde entdeckt, wie er mit den Investitionen der Menschen ins Ausland geflohen ist. Viele Menschen haben ihre Ersparnisse verloren. Der Skandal sorgt im Land für Aufsehen.",
            zh: "食品银行的老板被发现携带人民的投资逃往国外。许多人失去了他们的积蓄。丑闻在国内引起轩然大波。",
            es: "Se descubrió que el dueño del Banco de Alimentos huyó al extranjero con las inversiones de la gente. Muchas personas perdieron sus ahorros. El escándalo está causando revuelo en el país.",
            pt: "O proprietário do Banco de Alimentos foi descoberto fugindo para o exterior com os investimentos das pessoas. Muitas pessoas perderam suas economias. O escândalo está causando impacto no país.",
            ru: "Обнаружено, что владелец продовольственного банка сбежал за границу с инвестициями людей. Многие потеряли свои сбережения. Скандал вызвал резонанс в стране.",
        },
        effects: {
            internalSecurity: -10,
            publicSupport: -15,
            budget: -10,
        },
    },
    {
        id: 515,
        photo: waterPipesExploded,
        title: {
            tr: "Şehir Susuz Kaldı!",
            en: "City Left Without Water!",
            fr: "Ville Privée d'Eau!",
            de: "Stadt Ohne Wasser!",
            zh: "城市断水！",
            es: "¡Ciudad sin Agua!",
            pt: "Cidade Sem Água!",
            ru: "Город остался без воды!",
        },
        description: {
            tr: "Şehirdeki su boruları patladı, birçok semt saatlerce susuz kaldı. Sorunun çözülmesi için hummalı çalışmalar sürüyor.",
            en: "The city's water pipes burst, leaving many neighborhoods without water for hours. Intensive efforts are ongoing to resolve the issue.",
            fr: "Les canalisations d'eau de la ville ont éclaté, privant de nombreux quartiers d'eau pendant des heures. Des efforts intensifs sont en cours pour résoudre le problème.",
            de: "Die Wasserleitungen der Stadt sind geplatzt, wodurch viele Stadtteile stundenlang ohne Wasser auskommen mussten. Intensive Bemühungen zur Lösung des Problems sind im Gange.",
            zh: "城市的水管爆裂，许多街区数小时无水供应。目前正在努力解决问题。",
            es: "Las tuberías de agua de la ciudad estallaron, dejando a muchos barrios sin agua durante horas. Se están realizando esfuerzos intensivos para resolver el problema.",
            pt: "Os canos de água da cidade estouraram, deixando muitos bairros sem água por horas. Esforços intensivos estão em andamento para resolver o problema.",
            ru: "Водопроводные трубы города прорвало, оставив многие районы без воды на несколько часов. Проводятся интенсивные работы по устранению проблемы.",
        },
        effects: {
            infrastructureAndEnvironment: -15,
            publicSupport: -10,
            budget: -10,
        },
    },
    {
        id: 516,
        photo: womenAbuseOnstreet,
        title: {
            tr: "Sokak Ortasında Taciz!",
            en: "Harassment in the Street!",
            fr: "Harcèlement dans la Rue!",
            de: "Belästigung auf der Straße!",
            zh: "街头骚扰！",
            es: "¡Acoso en la Calle!",
            pt: "Assédio na Rua!",
            ru: "Домогательство на улице!",
        },
        description: {
            tr: "Gündüz vakti sokakta bir kadın taciz edildi. Halk bu duruma tepki gösteriyor. Güvenlik önlemleri yeniden gündemde.",
            en: "A woman was harassed in the street during the day. The public is reacting strongly. Security measures are back on the agenda.",
            fr: "Une femme a été harcelée dans la rue en plein jour. Le public réagit vivement. Les mesures de sécurité sont de nouveau à l'ordre du jour.",
            de: "Eine Frau wurde tagsüber auf der Straße belästigt. Die Öffentlichkeit reagiert stark. Sicherheitsmaßnahmen stehen wieder auf der Tagesordnung.",
            zh: "白天，一名女子在街头遭到骚扰。公众强烈反应，安全措施再次被提上议程。",
            es: "Una mujer fue acosada en la calle durante el día. El público está reaccionando con fuerza. Las medidas de seguridad vuelven a estar en la agenda.",
            pt: "Uma mulher foi assediada na rua durante o dia. O público está reagindo fortemente. As medidas de segurança estão de volta à agenda.",
            ru: "Днем на улице домогались до женщины. Общественность сильно реагирует. Меры безопасности снова на повестке дня.",
        },
        effects: {
            internalSecurity: -15,
            publicSupport: -15,
        },
    },
    {
        id: 517,
        photo: gangActivities,
        title: {
            tr: "Sokaklar Çetelere Kaldı!",
            en: "Streets Taken Over by Gangs!",
            fr: "Les Rues Sous le Contrôle des Gangs!",
            de: "Straßen von Gangs Übernommen!",
            zh: "街道被帮派占领！",
            es: "¡Las Calles Dominadas por Pandillas!",
            pt: "Ruas Tomadas por Gangues!",
            ru: "Улицы захвачены бандами!",
        },
        description: {
            tr: "Şehirde çete faaliyetleri artıyor, sokaklar tekinsiz hale geldi. Halk güvenlik endişesi yaşıyor.",
            en: "Gang activities are increasing in the city, and the streets have become unsafe. People are worried about security.",
            fr: "Les activités des gangs augmentent dans la ville, et les rues sont devenues peu sûres. Les gens s'inquiètent pour leur sécurité.",
            de: "Die Gangaktivitäten in der Stadt nehmen zu, und die Straßen sind unsicher geworden. Die Menschen machen sich Sorgen um ihre Sicherheit.",
            zh: "城市中的帮派活动日益增加，街道变得不安全。人们对安全感到担忧。",
            es: "Las actividades de pandillas están aumentando en la ciudad, y las calles se han vuelto inseguras. La gente está preocupada por la seguridad.",
            pt: "As atividades de gangues estão aumentando na cidade, e as ruas tornaram-se inseguras. As pessoas estão preocupadas com a segurança.",
            ru: "В городе растет активность банд, и улицы стали небезопасными. Люди обеспокоены безопасностью.",
        },
        effects: {
            internalSecurity: -15,
            publicSupport: -10,
        },
    },
    {
        id: 518,
        photo: politicianMercedes,
        title: {
            tr: "Milyon Dolarlık Makam Araçları!",
            en: "Million-Dollar Official Cars!",
            fr: "Voitures Officielles à un Million de Dollars!",
            de: "Millionen-Dollar-Dienstwagen!",
            zh: "价值百万美元的公务车！",
            es: "¡Coches Oficiales de Millones de Dólares!",
            pt: "Carros Oficiais de Milhões de Dólares!",
            ru: "Официальные автомобили за миллионы долларов!",
        },
        description: {
            tr: "Bazı politikacılar için son model makam araçları satın alındı. Halk bu harcamaları sorguluyor.",
            en: "Top-model official cars have been purchased for some politicians. The public questions these expenditures.",
            fr: "Des voitures officielles haut de gamme ont été achetées pour certains politiciens. Le public remet en question ces dépenses.",
            de: "Für einige Politiker wurden Top-Model-Dienstwagen gekauft. Die Öffentlichkeit hinterfragt diese Ausgaben.",
            zh: "为一些政客购买了顶级公务车。公众质疑这些开支。",
            es: "Se han comprado coches oficiales de alta gama para algunos políticos. El público cuestiona estos gastos.",
            pt: "Carros oficiais de alto padrão foram comprados para alguns políticos. O público questiona esses gastos.",
            ru: "Для некоторых политиков были приобретены автомобили премиум-класса. Общественность задается вопросом о целесообразности этих расходов.",
        },
        effects: {
            budget: -10,
            publicSupport: -10,
        },
    },
    {
        id: 519,
        photo: droughtLake,
        title: {
            tr: "12 Bin Yıllık Göl Kurutuldu!",
            en: "12,000-Year-Old Lake Drained!",
            fr: "Lac de 12 000 Ans Asséché!",
            de: "12.000 Jahre Alter See Ausgetrocknet!",
            zh: "一万二千年的湖被抽干了！",
            es: "¡Lago de 12,000 Años Secado!",
            pt: "Lago de 12 Mil Anos Seco!",
            ru: "12-тысячелетнее озеро осушено!",
        },
        description: {
            tr: "Maden aramak için 12 bin yıllık tarihi göl kurutuldu. Halk ve bilim insanları bu duruma tepkili, hükümet açıklama yapmak zorunda!",
            en: "A 12,000-year-old historic lake was drained to search for minerals. People and scientists are outraged, and the government must provide an explanation!",
            fr: "Un lac historique de 12 000 ans a été asséché pour chercher des minéraux. Les gens et les scientifiques sont outrés, et le gouvernement doit s'expliquer!",
            de: "Ein 12.000 Jahre alter historischer See wurde zur Suche nach Mineralien trockengelegt. Die Menschen und Wissenschaftler sind empört, und die Regierung muss eine Erklärung abgeben!",
            zh: "为了寻找矿产，一个有一万二千年历史的湖被抽干了。人们和科学家对此感到愤怒，政府必须作出解释！",
            es: "Un lago histórico de 12,000 años fue drenado para buscar minerales. La gente y los científicos están indignados, ¡y el gobierno debe dar una explicación!",
            pt: "Um lago histórico de 12.000 anos foi drenado para buscar minerais. As pessoas e os cientistas estão indignados, e o governo precisa fornecer uma explicação!",
            ru: "12-тысячелетнее историческое озеро осушено для поиска полезных ископаемых. Люди и ученые возмущены, и правительство должно дать объяснение!",
        },
        effects: {
            internationalRelations: -10,
            agriculturalProduction: -10,
            budget: -5,
        },
    },
    {
        id: 520,
        photo: gasDiscovery,
        title: {
            tr: "Kayıp Doğal Gaz Keşfi!",
            en: "Major Natural Gas Discovery!",
            fr: "Découverte Majeure de Gaz Naturel!",
            de: "Großer Erdgasfund!",
            zh: "重大发现：天然气！",
            es: "¡Descubrimiento Importante de Gas Natural!",
            pt: "Grande Descoberta de Gás Natural!",
            ru: "Крупное открытие природного газа!",
        },
        description: {
            tr: "Denizde büyük bir doğal gaz rezervi bulundu! Ekonomik krizle mücadele eden halk bu keşfi umutla karşıladı, ancak kaynakları verimli kullanmak adına gerekli yatırımlar yapılacak mı?",
            en: "A major natural gas reserve was discovered at sea! The crisis-stricken people welcomed this with hope, but will necessary investments be made to utilize the resources effectively?",
            fr: "Une grande réserve de gaz naturel a été découverte en mer! Le peuple frappé par la crise a accueilli cela avec espoir, mais des investissements nécessaires seront-ils faits pour utiliser efficacement les ressources?",
            de: "Ein großes Erdgasvorkommen wurde im Meer entdeckt! Die krisengeplagte Bevölkerung begrüßte dies hoffnungsvoll, aber werden notwendige Investitionen getätigt, um die Ressourcen effektiv zu nutzen?",
            zh: "在海上发现了一个重大的天然气储量！饱受危机的民众对此充满希望，但是否会进行必要的投资以有效利用资源？",
            es: "¡Se descubrió una gran reserva de gas natural en el mar! La gente afectada por la crisis recibió esto con esperanza, pero ¿se harán las inversiones necesarias para utilizar los recursos de manera efectiva?",
            pt: "Uma grande reserva de gás natural foi descoberta no mar! As pessoas afetadas pela crise receberam isso com esperança, mas serão feitos os investimentos necessários para utilizar os recursos de forma eficaz?",
            ru: "В море было обнаружено крупное месторождение природного газа! Люди, страдающие от кризиса, встретили это с надеждой, но будут ли сделаны необходимые инвестиции для эффективного использования ресурсов?",
        },
        effects: {
            budget: +20,
            publicSupport: +15,
        },
    },
    {
        id: 521,
        photo: damWaterShortage,
        title: {
            tr: "Kuraklık Alarmı: Barajlar Kuruyor!",
            en: "Drought Alert: Dams are Drying Up!",
            fr: "Alerte Sécheresse : Les Barrages S'assèchent!",
            de: "Dürrealarm: Staudämme Trocknen Aus!",
            zh: "干旱警报：水坝干涸！",
            es: "¡Alerta de Sequía: Los Embalses se Secan!",
            pt: "Alerta de Seca: Barragens Estão Secando!",
            ru: "Предупреждение о засухе: плотины пересыхают!",
        },
        description: {
            tr: "Yağışların yetersiz olması nedeniyle barajlardaki su seviyesi alarm verici düzeye indi. Su kesintileri gündemde, hükümet acil önlemler almaya hazırlanıyor.",
            en: "Due to insufficient rainfall, the water levels in the dams have dropped to alarming levels. Water cuts are on the agenda, and the government is preparing to take urgent measures.",
            fr: "En raison de précipitations insuffisantes, le niveau d'eau dans les barrages a atteint des niveaux alarmants. Les coupures d'eau sont à l'ordre du jour, et le gouvernement se prépare à prendre des mesures urgentes.",
            de: "Aufgrund unzureichender Niederschläge sind die Wasserstände in den Staudämmen auf alarmierende Werte gesunken. Wasserabschaltungen stehen auf der Tagesordnung, und die Regierung bereitet sich darauf vor, dringende Maßnahmen zu ergreifen.",
            zh: "由于降雨量不足，水坝的水位已经下降到令人担忧的水平。限水措施已提上议程，政府正准备采取紧急措施。",
            es: "Debido a la insuficiencia de lluvias, los niveles de agua en los embalses han caído a niveles alarmantes. Los cortes de agua están en la agenda, y el gobierno se prepara para tomar medidas urgentes.",
            pt: "Devido à insuficiência de chuvas, os níveis de água nas barragens caíram para níveis alarmantes. Cortes de água estão na agenda, e o governo se prepara para tomar medidas urgentes.",
            ru: "Из-за недостаточных осадков уровень воды в плотинах упал до тревожных значений. На повестке дня стоят отключения воды, и правительство готовится принять срочные меры.",
        },
        effects: {
            agriculturalProduction: -15,
        },
    },
    {
        id: 522,
        photo: mineCollapsed,
        title: {
            tr: "Maden Ocağında Göçük!",
            en: "Mine Collapse!",
            fr: "Effondrement dans une Mine!",
            de: "Einsturz in einer Mine!",
            zh: "矿井坍塌！",
            es: "¡Colapso en una Mina!",
            pt: "Colapso em uma Mina!",
            ru: "Обрушение в шахте!",
        },
        description: {
            tr: "Maden ocağında göçük meydana geldi. İşçiler mahsur kalırken, kurtarma ekipleri zamana karşı yarışıyor. Göçük olayı ülkede iş güvenliği konusunu tekrar gündeme getirdi.",
            en: "A mine collapse occurred. Workers are trapped as rescue teams race against time. The incident has brought workplace safety back into the spotlight in the country.",
            fr: "Un effondrement dans une mine s'est produit. Les ouvriers sont piégés alors que les équipes de secours luttent contre la montre. L'incident a remis la sécurité au travail sur le devant de la scène dans le pays.",
            de: "Ein Einsturz in einer Mine ereignete sich. Arbeiter sind eingeschlossen, während Rettungsteams gegen die Zeit kämpfen. Der Vorfall hat die Arbeitssicherheit im Land wieder ins Rampenlicht gerückt.",
            zh: "矿井发生坍塌。工人被困，救援队与时间赛跑。此事件让国家的工作安全问题再次成为关注焦点。",
            es: "Se produjo un colapso en una mina. Los trabajadores están atrapados mientras los equipos de rescate luchan contra el tiempo. El incidente ha vuelto a poner en el centro de atención la seguridad laboral en el país.",
            pt: "Ocorreu um colapso em uma mina. Trabalhadores estão presos enquanto as equipes de resgate correm contra o tempo. O incidente trouxe novamente à tona a segurança no trabalho no país.",
            ru: "В шахте произошел обвал. Рабочие оказались в ловушке, спасательные команды борются со временем. Этот инцидент вновь привлек внимание к вопросам безопасности на рабочих местах в стране.",
        },
        effects: {
            infrastructureAndEnvironment: -15,
            publicSupport: -10,
            internalSecurity: -15,
        },
    },
    {
        id: 523,
        photo: tourismSeason,
        title: {
            tr: "Turizm Sezonu Patlaması!",
            en: "Tourism Boom!",
            fr: "Explosion du Secteur Touristique!",
            de: "Tourismusboom!",
            zh: "旅游业繁荣！",
            es: "¡Boom del Turismo!",
            pt: "Explosão do Turismo!",
            ru: "Бум туризма!",
        },
        description: {
            tr: "Pandemi sonrası turizm sektörü büyük bir patlama yaşadı. Oteller dolup taşarken, esnaflar ekonomideki canlanmayı kutluyor.",
            en: "Post-pandemic, the tourism sector experienced a huge boom. Hotels are fully booked, and locals are celebrating the economic revival.",
            fr: "Après la pandémie, le secteur touristique a connu un essor considérable. Les hôtels sont complets et les habitants célèbrent la reprise économique.",
            de: "Nach der Pandemie erlebte der Tourismussektor einen großen Boom. Hotels sind ausgebucht, und die Einheimischen feiern die wirtschaftliche Erholung.",
            zh: "疫情过后，旅游业迎来了巨大的繁荣。酒店客满，当地人庆祝经济复苏。",
            es: "Después de la pandemia, el sector turístico experimentó un gran auge. Los hoteles están llenos y los lugareños celebran la reactivación económica.",
            pt: "Após a pandemia, o setor de turismo experimentou um grande boom. Os hotéis estão lotados e os moradores estão comemorando a recuperação econômica.",
            ru: "После пандемии туристический сектор пережил огромный бум. Отели переполнены, а местные жители празднуют экономическое возрождение.",
        },
        effects: {
            budget: +20,
            publicSupport: +10,
        },
    },
    {
        id: 524,
        photo: alperGezeravcı,
        title: {
            tr: "Uzaydaki ilk Yerli Astronot!",
            en: "First Local Astronaut in Space!",
            fr: "Le Premier Astronaute Local dans l'Espace!",
            de: "Erster Lokaler Astronaut im Weltraum!",
            zh: "第一位本地宇航员进入太空！",
            es: "¡El Primer Astronauta Local en el Espacio!",
            pt: "Primeiro Astronauta Local no Espaço!",
            ru: "Первый местный астронавт в космосе!",
        },
        description: {
            tr: "Ülkemizin ilk astronotu Alper Gezeravcı oldu! Halk gururla bu anı kutlarken, uzay çalışmaları hız kazanıyor.",
            en: "Our country's first astronaut, Alper Gezeravcı, has made it to space! The public celebrates this moment with pride, and space studies are gaining momentum.",
            fr: "Le premier astronaute de notre pays, Alper Gezeravcı, a atteint l'espace! Le public célèbre ce moment avec fierté et les études spatiales gagnent en élan.",
            de: "Der erste Astronaut unseres Landes, Alper Gezeravcı, hat es ins All geschafft! Die Öffentlichkeit feiert diesen Moment mit Stolz, und die Weltraumforschung gewinnt an Schwung.",
            zh: "我国的第一位宇航员阿尔普·盖泽拉夫奇进入了太空！公众怀着自豪庆祝这一时刻，太空研究正在加速发展。",
            es: "¡El primer astronauta de nuestro país, Alper Gezeravcı, ha llegado al espacio! El público celebra este momento con orgullo y los estudios espaciales están ganando impulso.",
            pt: "O primeiro astronauta do nosso país, Alper Gezeravcı, chegou ao espaço! O público celebra este momento com orgulho, e os estudos espaciais estão ganhando impulso.",
            ru: "Первый астронавт нашей страны, Альпер Гезеравчи, вышел в космос! Общественность с гордостью празднует этот момент, а космические исследования набирают обороты.",
        },
        effects: {
            internationalRelations: +10,
            publicSupport: +10,
        },
    },
    {
        id: 525,
        photo: forestFire,
        title: {
            tr: "Orman Yangını Felaketi!",
            en: "Forest Fire Disaster!",
            fr: "Catastrophe d'Incendie Forestier!",
            de: "Waldbrandkatastrophe!",
            zh: "森林火灾灾难！",
            es: "¡Desastre de Incendios Forestales!",
            pt: "Desastre de Incêndio Florestal!",
            ru: "Катастрофа лесного пожара!",
        },
        description: {
            tr: "Kıyı bölgelerinde büyük orman yangınları başladı! Hava sıcaklığı ve rüzgar nedeniyle alevler kontrol altına alınamıyor, yerleşim yerleri tehdit altında. Yangını söndürme çalışmaları devam ediyor.",
            en: "Large forest fires have broken out in coastal areas! Due to high temperatures and wind, the flames cannot be controlled, and settlements are under threat. Efforts to extinguish the fire continue.",
            fr: "De grands incendies de forêt se sont déclarés dans les zones côtières! En raison des températures élevées et du vent, les flammes ne peuvent être maîtrisées, et les habitations sont menacées. Les efforts pour éteindre l'incendie se poursuivent.",
            de: "In Küstengebieten sind große Waldbrände ausgebrochen! Aufgrund hoher Temperaturen und Wind können die Flammen nicht unter Kontrolle gebracht werden, und Siedlungen sind bedroht. Die Löscharbeiten dauern an.",
            zh: "沿海地区发生了大规模森林火灾！由于高温和大风，火焰无法控制，居民区受到威胁。灭火工作正在继续。",
            es: "¡Se han desatado grandes incendios forestales en las áreas costeras! Debido a las altas temperaturas y el viento, las llamas no pueden ser controladas y los asentamientos están bajo amenaza. Los esfuerzos para extinguir el fuego continúan.",
            pt: "Grandes incêndios florestais eclodiram em áreas costeiras! Devido às altas temperaturas e ao vento, as chamas não podem ser controladas e os assentamentos estão ameaçados. Os esforços para apagar o incêndio continuam.",
            ru: "В прибрежных районах вспыхнули крупные лесные пожары! Из-за высокой температуры и ветра пламя невозможно контролировать, населенные пункты под угрозой. Работы по тушению пожара продолжаются.",
        },
        effects: {
            agriculturalProduction: -15,
            budget: -5,
        },
    },
    {
        id: 526,
        photo: helaviyeIntervene,
        title: {
            tr: "Askeri Müdahale Helaviye’ye Genişliyor!",
            en: "Military Intervention Expands to Helaviye!",
            fr: "Intervention Militaire Élargie à Helaviye!",
            de: "Militärintervention Weitet sich auf Helaviye aus!",
            zh: "军事干预扩展到赫拉维耶！",
            es: "¡La Intervención Militar se Expande a Helaviye!",
            pt: "Intervenção Militar se Expande para Helaviye!",
            ru: "Военное вмешательство распространяется на Хелавие!",
        },
        description: {
            tr: "Ülkemiz, Helaviye’deki iç savaşa müdahale ediyor. Devlet kararıyla başlayan operasyonlar, uluslararası arenada tartışma yaratıyor.",
            en: "Our country is intervening in the civil war in Helaviye. The operations initiated by the state's decision are sparking debates on the international stage.",
            fr: "Notre pays intervient dans la guerre civile en Helaviye. Les opérations lancées par la décision de l'État suscitent des débats sur la scène internationale.",
            de: "Unser Land greift in den Bürgerkrieg in Helaviye ein. Die durch die Entscheidung des Staates eingeleiteten Operationen sorgen für Diskussionen auf der internationalen Bühne.",
            zh: "我国正在干预赫拉维耶的内战。国家决定发起的行动在国际舞台上引发了争议。",
            es: "Nuestro país está interviniendo en la guerra civil en Helaviye. Las operaciones iniciadas por decisión estatal están generando debates en el ámbito internacional.",
            pt: "Nosso país está intervindo na guerra civil em Helaviye. As operações iniciadas pela decisão do estado estão gerando debates no palco internacional.",
            ru: "Наша страна вмешивается в гражданскую войну в Хелавие. Операции, начатые по решению государства, вызывают споры на международной арене.",
        },
        effects: {
            internationalRelations: -20,
            budget: -10,
            internalSecurity: +15,
        },
    },
    {
        id: 527,
        photo: tbmmFight,
        title: {
            tr: "Meclis Birbirine Girdi!",
            en: "Parliament in Chaos!",
            fr: "Chaos au Parlement!",
            de: "Chaos im Parlament!",
            zh: "议会陷入混乱！",
            es: "¡Caos en el Parlamento!",
            pt: "Parlamento em Caos!",
            ru: "Хаос в парламенте!",
        },
        description: {
            tr: "Meclisteki oturumda iktidar ve muhalefet milletvekilleri arasında kavga çıktı. Meclis Başkanı olaya müdahale etmeye çalışırken, halk bu duruma tepki gösteriyor.",
            en: "A fight broke out between government and opposition MPs during the parliament session. While the Speaker of the House tried to intervene, the public reacted strongly to the situation.",
            fr: "Une bagarre a éclaté entre les députés du gouvernement et de l'opposition lors de la session parlementaire. Alors que le président de l'Assemblée tentait d'intervenir, le public a vivement réagi à la situation.",
            de: "Während der Parlamentssitzung brach ein Streit zwischen Regierungs- und Oppositionsabgeordneten aus. Während der Parlamentspräsident versuchte, einzugreifen, reagierte die Öffentlichkeit heftig auf die Situation.",
            zh: "在议会会议期间，政府和反对派议员之间爆发了争吵。众议院议长试图干预时，公众对此强烈反应。",
            es: "Durante la sesión parlamentaria, se desató una pelea entre los diputados del gobierno y de la oposición. Mientras el presidente del Parlamento intentaba intervenir, el público reaccionó fuertemente ante la situación.",
            pt: "Durante a sessão parlamentar, uma briga estourou entre os deputados do governo e da oposição. Enquanto o presidente da Câmara tentava intervir, o público reagiu fortemente à situação.",
            ru: "На заседании парламента разгорелась драка между депутатами от правительства и оппозиции. Спикер палаты пытался вмешаться, но общественность бурно отреагировала на ситуацию.",
        },
        effects: {
            publicSupport: -15,
            budget: -10,
        },
    },
    {
        id: 528,
        photo: angryPolitician,
        title: {
            tr: "Milletvekili Kürsüyü Yıktı!",
            en: "MP Topples Podium!",
            fr: "Un Député Renverse le Pupitre!",
            de: "Abgeordneter Stürzt das Podium!",
            zh: "议员推翻讲台！",
            es: "¡Un Diputado Derriba el Podio!",
            pt: "Deputado Derruba o Púlpito!",
            ru: "Депутат опрокинул трибуну!",
        },
        description: {
            tr: "Bir milletvekili, meclisteki oturumda kürsüyü yıktı! Olayın ardından hükümet ve muhalefet arasındaki gerilim tırmanıyor.",
            en: "An MP toppled the podium during a parliament session! After the incident, tensions between the government and opposition escalated.",
            fr: "Un député a renversé le pupitre lors d'une session parlementaire! Après l'incident, les tensions entre le gouvernement et l'opposition ont escaladé.",
            de: "Ein Abgeordneter stürzte das Podium während einer Parlamentssitzung! Nach dem Vorfall eskalierten die Spannungen zwischen Regierung und Opposition.",
            zh: "在议会会议期间，一名议员推翻了讲台！事件发生后，政府和反对派之间的紧张局势加剧。",
            es: "¡Un diputado derribó el podio durante una sesión parlamentaria! Tras el incidente, las tensiones entre el gobierno y la oposición aumentaron.",
            pt: "Um deputado derrubou o púlpito durante uma sessão parlamentar! Após o incidente, as tensões entre o governo e a oposição aumentaram.",
            ru: "На заседании парламента депутат опрокинул трибуну! После инцидента напряжение между правительством и оппозицией возросло.",
        },
        effects: {
            publicSupport: -10,
        },
    },
    {
        id: 529,
        photo: peopleLeavingCountry,
        title: {
            tr: "Beyin Göçü Artıyor!",
            en: "Brain Drain Intensifies!",
            fr: "L'Exode des Cerveaux s'Intensifie!",
            de: "Abwanderung von Talenten Nimmt zu!",
            zh: "人才流失加剧！",
            es: "¡Aumenta la Fuga de Cerebros!",
            pt: "A Fuga de Cérebros se Intensifica!",
            ru: "Интеллектуальная эмиграция усиливается!",
        },
        description: {
            tr: "Ülke ekonomisindeki kötü gidişat nedeniyle birçok vatandaş yurt dışına göç etmeye karar verdi. Ülkenin parlak beyinleri daha iyi bir hayat arayışında.",
            en: "Due to the country's worsening economy, many citizens have decided to migrate abroad. The nation's brightest minds are seeking a better life.",
            fr: "En raison de la détérioration de l'économie du pays, de nombreux citoyens ont décidé d'émigrer à l'étranger. Les esprits les plus brillants de la nation cherchent une vie meilleure.",
            de: "Aufgrund der sich verschlechternden Wirtschaft des Landes haben sich viele Bürger entschieden, ins Ausland auszuwandern. Die klügsten Köpfe der Nation suchen ein besseres Leben.",
            zh: "由于国家经济恶化，许多公民决定移居国外。国家中最聪明的人才正在寻找更好的生活。",
            es: "Debido al empeoramiento de la economía del país, muchos ciudadanos han decidido emigrar al extranjero. Las mentes más brillantes de la nación buscan una vida mejor.",
            pt: "Devido ao agravamento da economia do país, muitos cidadãos decidiram migrar para o exterior. As mentes mais brilhantes da nação estão buscando uma vida melhor.",
            ru: "Из-за ухудшающейся экономики страны многие граждане решили эмигрировать за границу. Самые умные умы нации ищут лучшей жизни.",
        },
        effects: {
            publicSupport: -15,
            infrastructureAndEnvironment: -15,
        },
    },
    {
        id: 531,
        photo: civilSubordinate,
        title: {
            tr: "Halk İsyan Etti!",
            en: "People Rebelled!",
            fr: "Le Peuple s'Est Révolté!",
            de: "Das Volk hat Rebelliert!",
            zh: "人民起义了！",
            es: "¡El Pueblo se Rebeló!",
            pt: "O Povo se Rebelou!",
            ru: "Народ восстал!",
        },
        description: {
            tr: "Hükümetin son dönemlerde aldığı kararlar nedeniyle halk sokaklara döküldü. İşsizlik, yoksulluk ve adaletsizlik karşısında halk isyan etti. Yetkililer çözüm arayışında.",
            en: "Due to recent government decisions, people have taken to the streets. Faced with unemployment, poverty, and injustice, the people rebelled. Authorities are seeking solutions.",
            fr: "En raison des récentes décisions gouvernementales, le peuple est descendu dans les rues. Face au chômage, à la pauvreté et à l'injustice, le peuple s'est révolté. Les autorités cherchent des solutions.",
            de: "Aufgrund der jüngsten Regierungsentscheidungen sind die Menschen auf die Straßen gegangen. Angesichts von Arbeitslosigkeit, Armut und Ungerechtigkeit hat das Volk rebelliert. Die Behörden suchen nach Lösungen.",
            zh: "由于最近的政府决策，人民走上街头。面对失业、贫困和不公正，人民起义了。当局正在寻求解决方案。",
            es: "Debido a las recientes decisiones del gobierno, la gente ha salido a las calles. Frente al desempleo, la pobreza y la injusticia, el pueblo se rebeló. Las autoridades están buscando soluciones.",
            pt: "Devido às recentes decisões do governo, as pessoas tomaram as ruas. Diante do desemprego, pobreza e injustiça, o povo se rebelou. As autoridades estão buscando soluções.",
            ru: "Из-за недавних решений правительства люди вышли на улицы. Перед лицом безработицы, бедности и несправедливости народ восстал. Власти ищут решения.",
        },
        effects: {
            publicSupport: -15,
            budget: -15,
            internalSecurity: -15,
        },
    },
    {
        id: 532,
        photo: civilSubordinate,
        title: {
            tr: "Çakarlı Araçlara Denetim!",
            en: "Inspection of Flashing Light Vehicles!",
            fr: "Inspection des Véhicules à Gyrophares!",
            de: "Kontrolle von Fahrzeugen mit Blaulicht!",
            zh: "检查闪光灯车辆！",
            es: "¡Inspección de Vehículos con Luces Intermitentes!",
            pt: "Inspeção de Veículos com Luzes Piscantes!",
            ru: "Проверка автомобилей с мигалками!",
        },
        description: {
            tr: "Devlet, usulsüz kullanılan çakarlı araçları trafikten men etti. Birçok araca ceza yazıldı. Emniyet güçleri denetimlerini artırıyor.",
            en: "The state has banned unauthorized flashing light vehicles from traffic. Many vehicles have been fined. Security forces are increasing inspections.",
            fr: "L'État a interdit la circulation des véhicules à gyrophares non autorisés. De nombreux véhicules ont été sanctionnés. Les forces de sécurité intensifient les contrôles.",
            de: "Der Staat hat nicht autorisierte Fahrzeuge mit Blaulicht aus dem Verkehr gezogen. Viele Fahrzeuge wurden mit Bußgeldern belegt. Die Sicherheitskräfte verstärken die Kontrollen.",
            zh: "国家已禁止未经授权的闪光灯车辆上路。许多车辆被罚款。安全部队正在加强检查。",
            es: "El estado ha prohibido los vehículos con luces intermitentes no autorizados en el tráfico. Muchos vehículos han sido multados. Las fuerzas de seguridad están aumentando las inspecciones.",
            pt: "O estado proibiu veículos com luzes piscantes não autorizadas de trafegar. Muitos veículos foram multados. As forças de segurança estão aumentando as inspeções.",
            ru: "Государство запретило движение автомобилей с несанкционированными мигалками. Многие машины были оштрафованы. Силы безопасности усиливают проверки.",
        },
        effects: {
            internalSecurity: +10,
            publicSupport: +10,
        },
    },
    {
        id: 533,
        photo: newFactoryOpening,
        title: {
            tr: "Ülkenin En Büyük Fabrikası Açıldı!",
            en: "The Country's Largest Factory Opened!",
            fr: "La Plus Grande Usine du Pays Inaugurée!",
            de: "Die Größte Fabrik des Landes Eröffnet!",
            zh: "国家最大工厂开业！",
            es: "¡Abierta la Fábrica Más Grande del País!",
            pt: "A Maior Fábrica do País Foi Inaugurada!",
            ru: "Открыта крупнейшая фабрика страны!",
        },
        description: {
            tr: "Ülkenin en büyük fabrikası açıldı! Fabrika, binlerce kişiye iş imkanı sağlayacak. Halk, bu yatırımı memnuniyetle karşılıyor.",
            en: "The country's largest factory has opened! The factory will provide thousands of jobs. People are welcoming this investment with satisfaction.",
            fr: "La plus grande usine du pays a été inaugurée! L'usine fournira des milliers d'emplois. Les habitants accueillent cet investissement avec satisfaction.",
            de: "Die größte Fabrik des Landes wurde eröffnet! Die Fabrik wird Tausende von Arbeitsplätzen schaffen. Die Menschen begrüßen diese Investition mit Zufriedenheit.",
            zh: "国家最大的工厂已经开业！这家工厂将提供数千个工作岗位。人们对这一投资表示满意。",
            es: "¡La fábrica más grande del país ha abierto sus puertas! La fábrica proporcionará miles de empleos. La gente recibe esta inversión con satisfacción.",
            pt: "A maior fábrica do país foi inaugurada! A fábrica criará milhares de empregos. As pessoas estão recebendo este investimento com satisfação.",
            ru: "В стране открылась крупнейшая фабрика! Завод обеспечит тысячи рабочих мест. Люди с удовлетворением приветствуют эту инвестицию.",
        },
        effects: {
            infrastructureAndEnvironment: +10,
            publicSupport: +10,
            budget: +10,
        },
    },
    {
        id: 534,
        photo: underSeaCables,
        title: {
            tr: "Denizaltı İnternet Kabloları Döşeniyor!",
            en: "Undersea Internet Cables Being Installed!",
            fr: "Pose de Câbles Internet Sous-Marins!",
            de: "Verlegung von Unterseekabeln für Internet!",
            zh: "海底互联网电缆正在铺设！",
            es: "¡Instalación de Cables de Internet Submarinos!",
            pt: "Instalação de Cabos Submarinos de Internet!",
            ru: "Прокладка подводных интернет-кабелей!",
        },
        description: {
            tr: "Denizaltı internet kabloları sayesinde ülkenin internet altyapısı genişliyor. Hızlı ve güvenilir internet erişimi sağlanacak. Teknolojiye yapılan bu yatırım halkı memnun ediyor.",
            en: "Undersea internet cables are expanding the country's internet infrastructure. Fast and reliable internet access will be provided. This investment in technology is pleasing the public.",
            fr: "Les câbles Internet sous-marins élargissent l'infrastructure Internet du pays. Un accès Internet rapide et fiable sera assuré. Cet investissement dans la technologie satisfait le public.",
            de: "Unterseekabel erweitern die Internetinfrastruktur des Landes. Schneller und zuverlässiger Internetzugang wird bereitgestellt. Diese Investition in Technologie erfreut die Bevölkerung.",
            zh: "海底互联网电缆正在扩展国家的互联网基础设施。将提供快速可靠的互联网接入。这项技术投资让公众感到满意。",
            es: "Los cables de internet submarinos están ampliando la infraestructura de internet del país. Se proporcionará acceso a internet rápido y confiable. Esta inversión en tecnología agrada al público.",
            pt: "Os cabos de internet submarinos estão expandindo a infraestrutura de internet do país. O acesso rápido e confiável à internet será garantido. Este investimento em tecnologia está agradando ao público.",
            ru: "Подводные интернет-кабели расширяют интернет-инфраструктуру страны. Будет обеспечен быстрый и надежный доступ в интернет. Эта инвестиция в технологии радует население.",
        },
        effects: {
            infrastructureAndEnvironment: +10,
            publicSupport: +10,
        },
    },
    {
        id: 535,
        photo: recycleFactory,
        title: {
            tr: "Geri Dönüşümde Büyük Atılım!",
            en: "A Major Leap in Recycling!",
            fr: "Un Grand Bond en Avant dans le Recyclage!",
            de: "Ein Großer Schritt im Recycling!",
            zh: "回收领域的重大飞跃！",
            es: "¡Un Gran Avance en el Reciclaje!",
            pt: "Um Grande Salto na Reciclagem!",
            ru: "Большой прорыв в переработке отходов!",
        },
        description: {
            tr: "Yurtdışından ithal edilen atıkların geri dönüşümü için yeni bir fabrika açıldı. Geri dönüşümde yapılan bu atılım, çevre kirliliğinin azalmasına katkı sağlayacak.",
            en: "A new factory has been opened to recycle imported waste. This leap in recycling will contribute to reducing environmental pollution.",
            fr: "Une nouvelle usine a été ouverte pour recycler les déchets importés. Ce progrès dans le recyclage contribuera à réduire la pollution environnementale.",
            de: "Eine neue Fabrik wurde eröffnet, um importierten Abfall zu recyceln. Dieser Fortschritt im Recycling wird dazu beitragen, die Umweltverschmutzung zu verringern.",
            zh: "一家新的工厂已经开放，用于回收进口废物。这一回收领域的飞跃将有助于减少环境污染。",
            es: "Se ha inaugurado una nueva fábrica para reciclar desechos importados. Este avance en el reciclaje contribuirá a reducir la contaminación ambiental.",
            pt: "Uma nova fábrica foi inaugurada para reciclar resíduos importados. Este avanço na reciclagem contribuirá para reduzir a poluição ambiental.",
            ru: "Открыт новый завод по переработке импортных отходов. Этот шаг в переработке отходов поможет снизить загрязнение окружающей среды.",
        },
        effects: {
            infrastructureAndEnvironment: +10,
            budget: +10,
        },
    },
    {
        id: 536,
        photo: spaceCenter,
        title: {
            tr: "İlk Uzay Merkezi Açıldı!",
            en: "The First Space Center Opened!",
            fr: "Le Premier Centre Spatial Ouvert!",
            de: "Das Erste Raumfahrtzentrum Eröffnet!",
            zh: "首个太空中心开放！",
            es: "¡Abierto el Primer Centro Espacial!",
            pt: "O Primeiro Centro Espacial Foi Aberto!",
            ru: "Открыт первый космический центр!",
        },
        description: {
            tr: "Ülkenin ilk uzay merkezi açıldı. Uzay çalışmaları ve keşifleri için büyük bir adım olan bu merkeze, halkın ilgisi büyük!",
            en: "The country's first space center has opened. This is a big step for space research and exploration, and the public is very interested!",
            fr: "Le premier centre spatial du pays a été inauguré. C'est un grand pas pour la recherche et l'exploration spatiales, et le public est très intéressé!",
            de: "Das erste Raumfahrtzentrum des Landes wurde eröffnet. Dies ist ein großer Schritt für die Raumfahrtforschung und -erforschung, und das Interesse der Öffentlichkeit ist groß!",
            zh: "该国的第一个太空中心已经开放。这是太空研究和探索的一个重要步骤，公众非常感兴趣！",
            es: "El primer centro espacial del país ha sido inaugurado. ¡Es un gran paso para la investigación y exploración espacial, y el público está muy interesado!",
            pt: "O primeiro centro espacial do país foi inaugurado. Este é um grande passo para a pesquisa e exploração espacial, e o público está muito interessado!",
            ru: "В стране открылся первый космический центр. Это большой шаг для космических исследований и открытий, и общественность проявляет большой интерес!",
        },
        effects: {
            infrastructureAndEnvironment: +10,
            publicSupport: +10,
            budget: +10,
        },
    },
    {
        id: 537,
        photo: farm,
        title: {
            tr: "Hayvancılığa Devlet Desteği!",
            en: "State Support for Animal Husbandry!",
            fr: "Soutien de l'État à l'Élevage!",
            de: "Staatliche Unterstützung für die Viehzucht!",
            zh: "国家支持畜牧业！",
            es: "¡Apoyo Estatal para la Ganadería!",
            pt: "Apoio Estatal à Pecuária!",
            ru: "Государственная поддержка животноводства!",
        },
        description: {
            tr: "Devlet, hayvancılığı desteklemek amacıyla çiftçilere yeni araçlar ve ekipmanlar sağladı. Hayvancılık sektörüne yapılan bu yatırım, tarım ve hayvancılığın önünü açacak.",
            en: "The state has provided farmers with new tools and equipment to support animal husbandry. This investment in the livestock sector will pave the way for agriculture and animal farming.",
            fr: "L'État a fourni aux agriculteurs de nouveaux outils et équipements pour soutenir l'élevage. Cet investissement dans le secteur de l'élevage ouvrira la voie à l'agriculture et à l'élevage.",
            de: "Der Staat hat den Landwirten neue Werkzeuge und Ausrüstungen zur Unterstützung der Viehzucht bereitgestellt. Diese Investition in den Viehzuchtsektor wird den Weg für Landwirtschaft und Tierhaltung ebnen.",
            zh: "国家为农民提供了新工具和设备以支持畜牧业。这项对畜牧业的投资将为农业和畜牧业铺平道路。",
            es: "El estado ha proporcionado a los agricultores nuevas herramientas y equipos para apoyar la ganadería. Esta inversión en el sector ganadero abrirá el camino para la agricultura y la ganadería.",
            pt: "O estado forneceu novos equipamentos e ferramentas aos agricultores para apoiar a pecuária. Este investimento no setor pecuário abrirá caminho para a agricultura e a criação de animais.",
            ru: "Государство предоставило фермерам новые инструменты и оборудование для поддержки животноводства. Эти инвестиции в сектор животноводства откроют путь для сельского хозяйства и животноводства.",
        },
        effects: {
            agriculturalProduction: +10,
            publicSupport: +10,
        },
    },
    {
        id: 538,
        photo: farmEducation,
        title: {
            tr: "Tarımsal Bilgilendirme Programları",
            en: "Agricultural Awareness Programs",
            fr: "Programmes de Sensibilisation Agricole",
            de: "Landwirtschaftliche Informationsprogramme",
            zh: "农业宣传计划",
            es: "Programas de Concienciación Agrícola",
            pt: "Programas de Sensibilização Agrícola",
            ru: "Программы повышения осведомленности в сельском хозяйстве",
        },
        description: {
            tr: "Tarım ve hayvancılık sektöründe bilinçli üretim için çiftçilere yönelik eğitim programları düzenleniyor.",
            en: "Educational programs are being organized for farmers to promote informed production in the agriculture and livestock sectors.",
            fr: "Des programmes éducatifs sont organisés pour les agriculteurs afin de promouvoir une production informée dans les secteurs de l'agriculture et de l'élevage.",
            de: "Bildungsprogramme werden für Landwirte organisiert, um eine informierte Produktion in den Bereichen Landwirtschaft und Viehzucht zu fördern.",
            zh: "正在为农民组织教育计划，以促进农业和畜牧业领域的知情生产。",
            es: "Se están organizando programas educativos para agricultores con el fin de promover una producción informada en los sectores agrícola y ganadero.",
            pt: "Estão sendo organizados programas educacionais para agricultores para promover uma produção informada nos setores de agricultura e pecuária.",
            ru: "Организуются образовательные программы для фермеров, чтобы способствовать осознанному производству в сельскохозяйственном и животноводческом секторах.",
        },
        effects: {
            agriculturalProduction: +10,
        },
    },
    {
        id: 539,
        photo: agricultureComp,
        title: {
            tr: "Dev Gıda Şirketi Yurtdışına Açılıyor!",
            en: "Major Food Company Expands Abroad!",
            fr: "Une Grande Entreprise Alimentaire S'Implante à l'Étranger!",
            de: "Großes Lebensmittelunternehmen Expandiert Ins Ausland!",
            zh: "大型食品公司进军海外！",
            es: "¡Gran Empresa Alimentaria se Expande al Extranjero!",
            pt: "Grande Empresa Alimentícia Expande-se para o Exterior!",
            ru: "Крупная пищевая компания выходит на зарубежный рынок!",
        },
        description: {
            tr: "Ülkemizin önde gelen gıda şirketlerinden biri, yurtdışına açılmaya karar verdi. Şirketin bu atılımı, ülke ekonomisine katkı sağlayacak.",
            en: "One of our country's leading food companies has decided to expand abroad. This move will contribute to the country's economy.",
            fr: "L'une des principales entreprises alimentaires de notre pays a décidé de s'implanter à l'étranger. Cette initiative contribuera à l'économie du pays.",
            de: "Eines der führenden Lebensmittelunternehmen unseres Landes hat beschlossen, ins Ausland zu expandieren. Dieser Schritt wird zur Wirtschaft des Landes beitragen.",
            zh: "我国领先的食品公司之一决定进军海外。这一举措将为国家经济作出贡献。",
            es: "Una de las principales empresas alimentarias de nuestro país ha decidido expandirse al extranjero. Este movimiento contribuirá a la economía del país.",
            pt: "Uma das principais empresas alimentícias do nosso país decidiu expandir-se para o exterior. Este movimento contribuirá para a economia do país.",
            ru: "Одна из ведущих пищевых компаний нашей страны решила выйти на зарубежный рынок. Этот шаг внесет вклад в экономику страны.",
        },
        effects: {
            agriculturalProduction: +10,
            publicSupport: +10,
        },
    },
    {
        id: 540,
        photo: scholarship,
        title: {
            tr: "Öğrenci Değişim Programı Genişletildi!",
            en: "Student Exchange Program Expanded!",
            fr: "Le Programme d'Échange Étudiant Élargi!",
            de: "Studentenaustauschprogramm Erweitert!",
            zh: "学生交换计划扩大！",
            es: "¡Programa de Intercambio Estudiantil Ampliado!",
            pt: "Programa de Intercâmbio Estudantil Ampliado!",
            ru: "Программа студенческого обмена расширена!",
        },
        description: {
            tr: "Üniversite öğrencileri arasında kültürel değişimi teşvik etmek amacıyla öğrenci değişim programı genişletildi.",
            en: "The student exchange program has been expanded to promote cultural exchange among university students.",
            fr: "Le programme d'échange étudiant a été élargi pour promouvoir les échanges culturels entre les étudiants universitaires.",
            de: "Das Studentenaustauschprogramm wurde erweitert, um den kulturellen Austausch unter Universitätsstudenten zu fördern.",
            zh: "学生交换计划已扩大，以促进大学生之间的文化交流。",
            es: "El programa de intercambio estudiantil se ha ampliado para promover el intercambio cultural entre los estudiantes universitarios.",
            pt: "O programa de intercâmbio estudantil foi ampliado para promover o intercâmbio cultural entre os estudantes universitários.",
            ru: "Программа студенческого обмена была расширена для продвижения культурного обмена среди студентов университетов.",
        },
        effects: {
            internationalRelations: +10,
            publicSupport: +10,
        },
    },
    {
        id: 541,
        photo: bribeMoney,
        title: {
            tr: "Rüşvet İddiaları Doğru Çıktı!",
            en: "Bribery Allegations Proven True!",
            fr: "Les Accusations de Corruption Confirmées!",
            de: "Bestechungsvorwürfe Bewahrheitet!",
            zh: "贿赂指控被证实属实！",
            es: "¡Se Confirmaron las Acusaciones de Soborno!",
            pt: "Acusações de Suborno Comprovadas!",
            ru: "Обвинения во взяточничестве подтвердились!",
        },
        description: {
            tr: "Ülkemizde ve yurtdışında faaliyet gösteren iki büyük şirketin üst düzey yöneticileri, rüşvet alırken yakalandı. Bu skandal, ülke gündemine bomba gibi düştü.",
            en: "Top executives of two major companies operating domestically and internationally were caught accepting bribes. This scandal has shaken the nation.",
            fr: "Des cadres supérieurs de deux grandes entreprises opérant au niveau national et international ont été surpris en train d'accepter des pots-de-vin. Ce scandale a secoué la nation.",
            de: "Führungskräfte zweier großer Unternehmen, die national und international tätig sind, wurden beim Annehmen von Bestechungsgeldern erwischt. Dieser Skandal hat das Land erschüttert.",
            zh: "两家在国内和国际上运营的大型公司的高管被发现接受贿赂。这一丑闻震惊了全国。",
            es: "Altos ejecutivos de dos grandes empresas que operan a nivel nacional e internacional fueron sorprendidos aceptando sobornos. Este escándalo ha sacudido a la nación.",
            pt: "Altos executivos de duas grandes empresas que operam nacional e internacionalmente foram apanhados aceitando subornos. Este escândalo abalou a nação.",
            ru: "Высшие руководители двух крупных компаний, работающих внутри страны и за рубежом, были пойманы на взяточничестве. Этот скандал потряс страну.",
        },
        effects: {
            internationalRelations: -10,
            publicSupport: -10,
            internalSecurity: -10,
        },
    },
    {
        id: 542,
        photo: censor,
        title: {
            tr: "Gazeteciliğe Sansür Engeli!",
            en: "Censorship Blocks Journalism!",
            fr: "La Censure Entrave le Journalisme!",
            de: "Zensur Blockiert Journalismus!",
            zh: "新闻业遭遇审查障碍！",
            es: "¡La Censura Bloquea el Periodismo!",
            pt: "Censura Bloqueia o Jornalismo!",
            ru: "Цензура мешает журналистике!",
        },
        description: {
            tr: "Adrenalin TV mensubu bir gazetecinin bakana sorduğu soru üzerine gözaltına alınması basın dünyasında büyük bir infial yarattı. Halk ve medya kuruluşları bu karara büyük tepki gösterirken uluslararası medyadan da bu da karara eleştiriler yağıyor.",
            en: "The detention of a journalist from Adrenalin TV for questioning a minister has caused outrage in the press world. The public and media organizations are reacting strongly, with international media also criticizing the decision.",
            fr: "La détention d'un journaliste d'Adrenalin TV pour avoir interrogé un ministre a provoqué un tollé dans le monde de la presse. Le public et les organisations médiatiques réagissent fortement, et les médias internationaux critiquent également la décision.",
            de: "Die Festnahme eines Journalisten von Adrenalin TV wegen der Befragung eines Ministers hat Empörung in der Pressewelt ausgelöst. Die Öffentlichkeit und Medienorganisationen reagieren heftig, während auch internationale Medien die Entscheidung kritisieren.",
            zh: "Adrenalin TV的一名记者因向部长提问而被拘留，这在新闻界引起了愤怒。公众和媒体组织反应强烈，国际媒体也对这一决定提出批评。",
            es: "La detención de un periodista de Adrenalin TV por cuestionar a un ministro ha provocado indignación en el mundo de la prensa. El público y las organizaciones mediáticas están reaccionando con fuerza, y los medios internacionales también critican la decisión.",
            pt: "A detenção de um jornalista da Adrenalin TV por questionar um ministro causou indignação no mundo da imprensa. O público e as organizações de mídia estão reagindo fortemente, com a mídia internacional também criticando a decisão.",
            ru: "Задержание журналиста Adrenalin TV за вопрос министру вызвало возмущение в мире прессы. Общественность и медиа-организации активно реагируют, а международные СМИ также критикуют это решение.",
        },
        effects: {
            internationalRelations: -15,
            publicSupport: -15,
        },
    },
    {
        id: 543,
        photo: wasteFruit,
        title: {
            tr: "Çiftçinin Ürettiği Elinde Kaldı!",
            en: "Farmers' Produce Left Unsold!",
            fr: "Les Produits des Agriculteurs Restent Invendus!",
            de: "Die Erzeugnisse der Bauern Bleiben Unverkauft!",
            zh: "农民的农产品滞销！",
            es: "¡Los Productos de los Agricultores se Quedan sin Vender!",
            pt: "Produtos dos Agricultores Ficam Encalhados!",
            ru: "Продукция фермеров осталась непроданной!",
        },
        description: {
            tr: "Toptancıların teklif ettiği düşük fiyatlar yüzünden çiftçiler isyan etti. Ürettiklerinin karşılığını alamayan çiftçiler, ürünlerinin bir kısmını halka dağıtırken çoğunu da çöpe dökmek zorunda kaldı.",
            en: "Farmers revolted due to the low prices offered by wholesalers. Unable to earn a fair price, they distributed some of their produce to the public but had to dump most of it.",
            fr: "Les agriculteurs se sont révoltés en raison des bas prix proposés par les grossistes. Incapables de tirer un prix équitable, ils ont distribué une partie de leurs produits au public mais ont dû jeter le reste.",
            de: "Die Bauern rebellierten wegen der niedrigen Preise, die von Großhändlern angeboten wurden. Da sie keinen fairen Preis erzielen konnten, verteilten sie einen Teil ihrer Erzeugnisse an die Öffentlichkeit, mussten aber den größten Teil wegwerfen.",
            zh: "由于批发商提供的低价，农民们感到愤怒。他们无法获得公平的价格，一部分农产品分发给了公众，但大部分不得不被丢弃。",
            es: "Los agricultores se rebelaron debido a los bajos precios ofrecidos por los mayoristas. Incapaces de obtener un precio justo, distribuyeron parte de sus productos al público pero tuvieron que desechar la mayoría.",
            pt: "Os agricultores revoltaram-se devido aos baixos preços oferecidos pelos atacadistas. Sem conseguir um preço justo, distribuíram parte de seus produtos ao público, mas tiveram que descartar a maioria.",
            ru: "Фермеры восстали из-за низких цен, предложенных оптовиками. Не получив справедливой цены, они раздали часть своей продукции населению, но большую часть пришлось выбросить.",
        },
        effects: {
            agriculturalProduction: -15,
            budget: -15,
        },
    },
    {
        id: 544,
        photo: getSick,
        title: {
            tr: "Hastalandın!",
            en: "You Got Sick!",
            fr: "Tu Es Tombé Malade!",
            de: "Du Bist Krank Geworden!",
            zh: "你生病了！",
            es: "¡Te Has Enfermedado!",
            pt: "Você Ficou Doente!",
            ru: "Ты заболел!",
        },
        description: {
            tr: "Yorucu bir iş gününün sonunda hastalandın. Evde tedavi oluyorsun. Meydanı boş bıraktığın için halk üzerindeki nüfuzun azalmaya başladı.",
            en: "After a tiring workday, you got sick. You're recovering at home. Your absence has started to reduce your influence over the public.",
            fr: "Après une journée de travail épuisante, tu es tombé malade. Tu te soignes chez toi. Ton absence commence à réduire ton influence sur le public.",
            de: "Nach einem anstrengenden Arbeitstag bist du krank geworden. Du erholst dich zu Hause. Deine Abwesenheit beginnt, deinen Einfluss auf die Öffentlichkeit zu verringern.",
            zh: "在辛苦的一天工作后，你生病了。你正在家里康复。你的缺席开始削弱你对公众的影响力。",
            es: "Después de un día de trabajo agotador, te enfermaste. Estás recuperándote en casa. Tu ausencia ha comenzado a reducir tu influencia sobre el público.",
            pt: "Após um dia de trabalho cansativo, você ficou doente. Você está se recuperando em casa. Sua ausência começou a reduzir sua influência sobre o público.",
            ru: "После утомительного рабочего дня ты заболел. Ты лечишься дома. Твое отсутствие начинает уменьшать твое влияние на общественность.",
        },
        effects: {
            publicSupport: -10,
            internationalRelations: -10,
        },
    },
    {
        id: 545,
        photo: illuminati,
        title: {
            tr: "Fulnansa Olimpiyatlarında Korkutan Ritüel!",
            en: "Terrifying Ritual at Fulnansa Olympics!",
            fr: "Rituel Terrifiant aux Jeux Olympiques de Fulnansa!",
            de: "Erschreckendes Ritual bei den Fulnansa-Olympischen Spielen!",
            zh: "弗尔南萨奥运会的恐怖仪式！",
            es: "¡Ritual Aterrador en los Juegos Olímpicos de Fulnansa!",
            pt: "Ritual Aterrorizante nas Olimpíadas de Fulnansa!",
            ru: "Пугающий ритуал на Олимпиаде в Фулнансе!",
        },
        description: {
            tr: "Fulnansa Olimpiyatları'nda yapılan açılış töreninde birbirinden ilginç ve ürkütücü ritüeller gerçekleşti. Bu durum dünya çapında gerginlik yarattı.",
            en: "At the Fulnansa Olympics opening ceremony, bizarre and terrifying rituals were performed. This caused global tensions.",
            fr: "Lors de la cérémonie d'ouverture des Jeux Olympiques de Fulnansa, des rituels bizarres et terrifiants ont été réalisés. Cela a causé des tensions mondiales.",
            de: "Bei der Eröffnungsfeier der Fulnansa-Olympischen Spiele wurden bizarre und erschreckende Rituale durchgeführt. Dies führte zu globalen Spannungen.",
            zh: "在弗尔南萨奥运会的开幕式上，进行了奇怪而可怕的仪式。这引起了全球紧张局势。",
            es: "En la ceremonia de apertura de los Juegos Olímpicos de Fulnansa se realizaron rituales extraños y aterradores. Esto causó tensiones globales.",
            pt: "Na cerimônia de abertura das Olimpíadas de Fulnansa, rituais bizarros e aterrorizantes foram realizados. Isso causou tensões globais.",
            ru: "На церемонии открытия Олимпийских игр в Фулнансе были проведены странные и пугающие ритуалы. Это вызвало глобальную напряженность.",
        },
        effects: {
            internationalRelations: -15,
        },
    },
    {
        id: 546,
        photo: meteor,
        title: {
            tr: "Pasifik Okyanusuna Dev Göktaşı Düştü!",
            en: "Massive Meteor Crashes into the Pacific Ocean!",
            fr: "Un Énorme Météorite S'Écrase dans l'Océan Pacifique!",
            de: "Riesiger Meteorit Stürzt in den Pazifik!",
            zh: "巨大的陨石坠入太平洋！",
            es: "¡Enorme Meteorito se Estrella en el Océano Pacífico!",
            pt: "Enorme Meteoro Cai no Oceano Pacífico!",
            ru: "Огромный метеорит упал в Тихий океан!",
        },
        description: {
            tr: "Biliminsanlarının sadece birkaç saat önce fark ettiği dev göktaşı, Pasifik Okyanusu'na düştü. Dünya çapında büyük endişe yaratan olay, bilim insanlarını ve hükümetleri harekete geçirdi.",
            en: "A massive meteor, detected just hours earlier by scientists, crashed into the Pacific Ocean. This globally concerning event has mobilized scientists and governments.",
            fr: "Un énorme météorite, détecté quelques heures plus tôt par des scientifiques, s'est écrasé dans l'océan Pacifique. Cet événement préoccupant à l'échelle mondiale a mobilisé scientifiques et gouvernements.",
            de: "Ein riesiger Meteorit, der erst wenige Stunden zuvor von Wissenschaftlern entdeckt wurde, stürzte in den Pazifik. Dieses global beunruhigende Ereignis hat Wissenschaftler und Regierungen mobilisiert.",
            zh: "科学家仅在几小时前发现的一颗巨型陨石坠入了太平洋。这一全球关注的事件动员了科学家和各国政府。",
            es: "Un enorme meteorito, detectado solo unas horas antes por científicos, se estrelló en el Océano Pacífico. Este evento preocupante a nivel mundial ha movilizado a científicos y gobiernos.",
            pt: "Um enorme meteoro, detectado apenas algumas horas antes por cientistas, caiu no Oceano Pacífico. Este evento preocupante globalmente mobilizou cientistas e governos.",
            ru: "Огромный метеорит, обнаруженный учеными всего за несколько часов до этого, упал в Тихий океан. Это глобально обеспокоившее событие мобилизовало ученых и правительства.",
        },
        effects: {
            internationalRelations: -15,
            internalSecurity: -15,
        },
    },
    {
        id: 547,
        photo: pandemic,
        title: {
            tr: "Dünya Genelinde Yeni Bir Pandemi!",
            en: "A New Global Pandemic!",
            fr: "Une Nouvelle Pandémie Mondiale!",
            de: "Eine Neue Globale Pandemie!",
            zh: "全球范围内的新疫情！",
            es: "¡Una Nueva Pandemia Global!",
            pt: "Uma Nova Pandemia Global!",
            ru: "Новая глобальная пандемия!",
        },
        description: {
            tr: "Dünya genelinde yayılan yeni bir virüs milyonlarca insanın ölümüne sebep oldu. Ülkeler kendi sınırlarını kapatırken, halk sağlık ve güvenlik endişesi yaşıyor.",
            en: "A new virus spreading globally has caused millions of deaths. Countries are closing their borders, and people are concerned about health and security.",
            fr: "Un nouveau virus se propageant dans le monde entier a causé des millions de décès. Les pays ferment leurs frontières et les gens s'inquiètent pour leur santé et leur sécurité.",
            de: "Ein neues, weltweit verbreitetes Virus hat Millionen von Todesfällen verursacht. Länder schließen ihre Grenzen, und die Menschen sind besorgt über Gesundheit und Sicherheit.",
            zh: "一种新的全球传播的病毒已经导致数百万人死亡。各国正在关闭边界，民众对健康和安全感到担忧。",
            es: "Un nuevo virus que se está propagando globalmente ha causado millones de muertes. Los países están cerrando sus fronteras, y la gente está preocupada por la salud y la seguridad.",
            pt: "Um novo vírus que está se espalhando globalmente causou milhões de mortes. Os países estão fechando suas fronteiras, e as pessoas estão preocupadas com a saúde e a segurança.",
            ru: "Новый вирус, распространяющийся по всему миру, вызвал миллионы смертей. Страны закрывают свои границы, а люди обеспокоены здоровьем и безопасностью.",
        },
        effects: {
            internationalRelations: -20,
            budget: -15,
            publicSupport: -15,
        },
    },
];